graphql.graphql_servers.*:
  type: config_entity
  label: 'Server'
  mapping:
    name:
      type: string
      label: 'Name'
    label:
      type: string
      label: 'Label'
    endpoint:
      type: string
      label: 'Endpoint'
    debug_flag:
      type: integer
      label: 'Debug Flag'
    schema:
      type: string
      label: 'Schema'
    caching:
      type: boolean
      label: 'Caching'
    batching:
      type: boolean
      label: 'Batching'
    schema_configuration:
      type: 'graphql.schema.[%parent.schema]'
    persisted_queries_settings:
      type: sequence
      label: 'Persisted queries settings'
      orderby: key
      sequence:
        type: plugin.plugin_configuration.persisted_query.[%key]
        label: 'The configuration for a single persisted query plugin.'

graphql.schema.*:
  type: mapping
  label: 'Schema settings'

graphql.schema.composable:
  type: mapping
  label: 'Composable schema'
  mapping:
    extensions:
      label: Enabled extensions
      type: sequence
      sequence:
        type: boolean

graphql.default_persisted_query_configuration:
  type: mapping
  label: 'Persisted query settings'
  mapping:
    weight:
      type: integer
      label: 'The weight'

plugin.plugin_configuration.persisted_query.*:
  type: graphql.default_persisted_query_configuration
